### ISSUE TITLE
如何选择 Linux 操作系统

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [seismo-learn/seismology101#160]
如题。
Fedora 和 Ubuntu 相比有哪些优缺点，不同研究方向的人该如何选择？
用 Centos 的人也很多，Centos Stream 与 Centos7，8 相比到底有什么区别？

我觉得目前 “选择操作系统” 一节介绍的过于简单，对于刚接触 Linux 的人来说有些茫然失措。

**Comment by core-man** [comment]
> 如题。
> Fedora 和 Ubuntu 相比有哪些优缺点，不同研究方向的人该如何选择？
> 用 Centos 的人也很多，Centos Stream 与 Centos7，8 相比到底有什么区别？
> 
> 我觉得目前 “选择操作系统” 一节介绍的过于简单，对于刚接触 Linux 的人来说有些茫然失措。

The difference among different linux distributions is a good issue.

Dongdong and I have discussed this question in wechat at the beginning. Both of us prefer Fedora. But since a lot of people use Ubuntu, we also list it. In fact, we do not recommend CentOS, and that is the reason we don't have a CentOS setup.

At last, we put Fedora at the first part. Since this is Linux101, I think we should not list the detailed comparisons among those Linux distributions. Both Fedora and Ubuntun are okay. New babies can choose any one.

**Comment by seisman** [comment]
We want the keep the tutorial short, so we don't want to mention the differences. 

For anyone who is new to Linux, they should follow our recommendations.

For anyone who knows a little about Linux and questions our recommendation, they should just google it to find the best distro he like.
